"""hapus coba

Revision ID: 9a2327dc022c
Revises: 1a53c147cbc4
Create Date: 2025-01-11 02:41:31.999335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a2327dc022c'
down_revision: Union[str, None] = '1a53c147cbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coba')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coba', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
